version: '3'
services:
  influxdb:
    image: influxdb

  telegraf:
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf
    links:
    - influxdb
    - breakit
    image: telegraf
    depends_on:
    - influxdb

  kapacitor:
    image: kapacitor
    volumes:
    - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf
    - kapacitor_sockets:/sockets
    links:
    - influxdb
    - golerta
    depends_on:
    - influxdb

  morgoth:
    build:
      context: morgoth/
    volumes:
      - kapacitor_sockets:/sockets
    ports:
    - "6767:6767"

  chronograf:
    image: chronograf
    links:
    - influxdb
    - kapacitor
    ports:
    - "8888:8888"
    depends_on:
    - influxdb
    - kapacitor
    environment:
    - INFLUXDB_URL=http://influxdb:8086
    - KAPACITOR_URL=http://kapacitor:9092

  grafana:
    image: grafana/grafana
    links:
      - influxdb
    ports:
    - "3000:3000"
    depends_on:
    - influxdb

  rethinkdb:
    image: rethinkdb
    ports:
    - "8080:8080"

  golerta:
    build:
      context: https://github.com/allen13/golerta.git#feature/viper-config
    volumes:
    - ./golerta.toml:/golerta.toml
    environment:
    - GOLERTA_RETHINKDB_ADDRESS=rethinkdb:28015
    ports:
    - "5608:5608"
    links:
    - rethinkdb
    depends_on:
    - rethinkdb

  breakit:
    build:
      context: breakit/
    ports:
    - "1323:1323"

volumes:
  kapacitor_sockets:
